parent_config: ['./conf/nli/esim.yaml', './conf/nli/fever/abstract_snli.yaml']

# fixed experiment seed
seed: 1337
dropout: 0.2
repr_dim: 300
validation_interval: 10000
learning_rate: 0.0004
learning_rate_decay: 0.9
batch_size: 24
epochs: 5
reader: 'pytorch_depsa_esim_elmo_reader'
embedding_dim: 128
self_attention: True