description: >
  Basic multiple choice configuration.

parent_config: './conf/jack.yaml'

assertion_dir: 'data/knowledge_integration/knowledge_store'
assertion_limit: 20
assertion_sources: ['conceptnet']

reading_module:
  - input: 'text'
    module: 'lstm'
    with_projection: True
    activation: relu


seed: 1337

reader: 'cbilstm_nli_assertion_reader'
save_dir: './cbilstm_nli_assertion_reader'

loader: snli

train: 'data/MultiNLI/multinli_1.0/multinli_1.0_train.jsonl'
dev: 'data/MultiNLI/multinli_1.0/multinli_1.0_dev.jsonl'

embedding_format: 'memory_map_dir'
embedding_file: 'data/GloVe/glove.840B.300d.memory_map_dir'

vocab_from_embeddings: True
with_char_embeddings: True

repr_dim: 300
epochs: 20
dropout: 0.2
batch_size: 128
